### PR TITLE
fix: logs not being integrated with the `path-prefix` correctly

### LINKED ISSUE #2548: `route_prefix` breaks WebUI
When you have `route_prefix` set the webui ignores it. My suggestion would either be to a) follow the `route_prefix` or b) have the webui served on `/` to keep it private while the actual api is served on `route_prefix`.

Image

### PR DESCRIPTION
**Pull request by CommanderStorm**
Resolves https://github.com/maplibre/martin/issues/2548

### CODE REVIEW

File: martin/src/bin/martin.rs [hunk 1]
```diff
@@ -37,13 +37,26 @@ async fn start(args: Args) -> MartinResult<()> {
...
-    info!("Martin has been started on {listen_addresses}.");
-    info!("Use http://{listen_addresses}/catalog to get the list of available sources.");
+
+    let base_url = if let Some(ref prefix) = route_prefix {
+        format!("http://{listen_addresses}{prefix}")
+    } else {
+        format!("http://{listen_addresses}")
+    };
+
+    if let Some(ref prefix) = route_prefix {
```
Comment (nyurik) [inline martin/src/bin/martin.rs]: while this is all good, I wonder if we should simplify this message to a single line with a clickable link only? I.e. keeping it simple, something like this when UI is available:

```
Martin server is now active at http://localhost:3000/
```

or point to the catalog when UI is off?

File: martin/src/bin/martin.rs [hunk 2]
```diff
@@ -37,13 +37,26 @@ async fn start(args: Args) -> MartinResult<()> {
...
+        info!("Martin has been started on {listen_addresses} with route prefix '{prefix}'.");
+    } else {
+        info!("Martin has been started on {listen_addresses}.");
+    }
+    info!("Use {base_url}/catalog to get the list of available sources.");
 
     #[cfg(all(feature = "webui", not(docsrs)))]
     if web_ui_mode == martin::config::args::WebUiMode::EnableForAll {
-        tracing::warn!("Web UI is enabled for all connections at http://{listen_addresses}/");
+        tracing::warn!("Web UI is enabled for all connections at {base_url}/");
```
Comment (nyurik) [inline martin/src/bin/martin.rs]: probably better not to have a trailing slash?

**Review by nyurik — APPROVED** [review]
looks ok, but do consider my other comments before merging

File: martin/src/bin/martin.rs (hunk 2 above)
Comment (CommanderStorm) [reply martin/src/bin/martin.rs]: No, that is required. Otherwise our UI does not work

File: martin/src/bin/martin.rs [hunk 3]
```diff
@@ -37,13 +37,26 @@ async fn start(args: Args) -> MartinResult<()> {
...
+    } else {
+        format!("http://{listen_addresses}")
+    };
+
+    if let Some(ref prefix) = route_prefix {
+        info!("Martin has been started on {listen_addresses} with route prefix '{prefix}'.");
+    } else {
+        info!("Martin has been started on {listen_addresses}.");
+    }
+    info!("Use {base_url}/catalog to get the list of available sources.");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
```

File: martin/src/bin/martin.rs
Comment (CommanderStorm) [inline martin/src/bin/martin.rs:58]:
```suggestion
tracing::warn!("Martin server is now active at {base_url}/");
```

File: martin/src/bin/martin.rs [hunk 4]
```diff
@@ -37,19 +37,25 @@ async fn start(args: Args) -> MartinResult<()> {
...
+    let base_url = if let Some(ref prefix) = route_prefix {
+        format!("http://{listen_addresses}{prefix}")
+    } else {
+        format!("http://{listen_addresses}")
+    };
 
     #[cfg(all(feature = "webui", not(docsrs)))]
     if web_ui_mode == martin::config::args::WebUiMode::EnableForAll {
-        tracing::warn!("Web UI is enabled for all connections at http://{listen_addresses}/");
+        tracing::warn!("Web UI is enabled for all connections at {base_url}/");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
        tracing::info!("Martin server is now active at {base_url}/"");
```

File: martin/src/bin/martin.rs [hunk 5]
```diff
@@ -37,19 +37,25 @@ async fn start(args: Args) -> MartinResult<()> {
...
     } else {
         info!(
             "Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
         );
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs:54]:
```suggestion
info!(
"Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
);
info!(
"Martin server is now active. Visit {base_url}/catalog to see all the sources avaliable");
```

File: martin/src/bin/martin.rs [hunk 6]
```diff
@@ -37,19 +37,25 @@ async fn start(args: Args) -> MartinResult<()> {
...
     }
-
+tracing::warn!("Martin server is now active at {base_url}/");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion

```

File: martin/src/bin/martin.rs [hunk 7]
```diff
@@ -37,19 +37,27 @@ async fn start(args: Args) -> MartinResult<()> {
...
-            "Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
-        );
+info!(
+"Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
+);
+info!(
+"Martin server is now active. Visit {base_url}/catalog to see all the sources avaliable");
     }
-
+    tracing::warn!("Martin server is now active at {base_url}/");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
```

File: martin/src/bin/martin.rs [hunk 8]
```diff
@@ -37,19 +37,26 @@ async fn start(args: Args) -> MartinResult<()> {
...
+
     let (server, listen_addresses) = new_server(config.srv, sources)?;
-    info!("Martin has been started on {listen_addresses}.");
-    info!("Use http://{listen_addresses}/catalog to get the list of available sources.");
+
+    let base_url = if let Some(ref prefix) = route_prefix {
+        format!("http://{listen_addresses}{prefix}")
+    } else {
+        format!("http://{listen_addresses}")
+    };
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
```

File: martin/src/bin/martin.rs [hunk 9]
```diff
@@ -37,19 +37,26 @@ async fn start(args: Args) -> MartinResult<()> {
     #[cfg(all(feature = "webui", not(docsrs)))]
     let web_ui_mode = config.srv.web_ui.unwrap_or_default();
 
+    let route_prefix = config.srv.route_prefix.clone();
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs:40]:
```suggestion
    let base_url = if let Some(ref prefix) = config.srv.route_prefix {
        format!("http://{listen_addresses}{prefix}")
    } else {
        format!("http://{listen_addresses}")
    };
```

File: martin/src/bin/martin.rs [hunk 10]
```diff
@@ -37,19 +37,24 @@ async fn start(args: Args) -> MartinResult<()> {
...
+        tracing::info!("Martin server is now active at {base_url}/"");
     } else {
-        info!(
-            "Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
-        );
+info!(
+"Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
+);
+info!(
+"Martin server is now active. Visit {base_url}/catalog to see all the sources avaliable");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
        info!("Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections.");
        info!("Martin server is now active. Visit {base_url}/catalog to see all the sources avaliable");
```

File: martin/src/bin/martin.rs [hunk 11]
```diff
@@ -37,19 +37,21 @@ async fn start(args: Args) -> MartinResult<()> {
...
+    };
+
     let (server, listen_addresses) = new_server(config.srv, sources)?;
-    info!("Martin has been started on {listen_addresses}.");
-    info!("Use http://{listen_addresses}/catalog to get the list of available sources.");
 
     #[cfg(all(feature = "webui", not(docsrs)))]
     if web_ui_mode == martin::config::args::WebUiMode::EnableForAll {
-        tracing::warn!("Web UI is enabled for all connections at http://{listen_addresses}/");
+        tracing::info!("Martin server is now active at {base_url}/"");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
        tracing::info!("Martin server is now active at {base_url}/");
```

**Review by nyurik — APPROVED** [review]

File: martin/src/bin/martin.rs [hunk 12]
```diff
@@ -37,19 +37,25 @@ async fn start(args: Args) -> MartinResult<()> {
...
+    };
+
     let (server, listen_addresses) = new_server(config.srv, sources)?;
-    info!("Martin has been started on {listen_addresses}.");
-    info!("Use http://{listen_addresses}/catalog to get the list of available sources.");
 
     #[cfg(all(feature = "webui", not(docsrs)))]
     if web_ui_mode == martin::config::args::WebUiMode::EnableForAll {
-        tracing::warn!("Web UI is enabled for all connections at http://{listen_addresses}/");
+        tracing::info!("Martin server is now active at {base_url}");
```
Comment (nyurik) [inline martin/src/bin/martin.rs:50]: why do we use both `info!` and `tracing::info!` in the same file?

Comment (CommanderStorm) [reply martin/src/bin/martin.rs:50]: this here is guarded by the cfg, the other is imported actually.

Since we have the no-unused imports, it is either this or ugly/hard to maintain cfg imports at the top

File: martin/src/bin/martin.rs [hunk 13]
```diff
@@ -37,19 +37,23 @@ async fn start(args: Args) -> MartinResult<()> {
     #[cfg(all(feature = "webui", not(docsrs)))]
     let web_ui_mode = config.srv.web_ui.unwrap_or_default();
 
+    let base_url = if let Some(ref prefix) = config.srv.route_prefix {
+        format!("http://{listen_addresses}{prefix}/")
+    } else {
+        format!("http://{listen_addresses}/")
+    };
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs:46]:
```suggestion
    let route_prefix = config.srv.route_prefix.clone();
```

File: martin/src/bin/martin.rs [hunk 14]
```diff
@@ -37,19 +37,23 @@ async fn start(args: Args) -> MartinResult<()> {
...
+
     let (server, listen_addresses) = new_server(config.srv, sources)?;
-    info!("Martin has been started on {listen_addresses}.");
-    info!("Use http://{listen_addresses}/catalog to get the list of available sources.");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs:47]:
```suggestion
let base_url = if let Some(ref prefix) = route_prefix {
        format!("http://{listen_addresses}{prefix}/")
    } else {
        format!("http://{listen_addresses}/")
    };

```

File: martin/src/bin/martin.rs [hunk 15]
```diff
@@ -37,19 +37,28 @@ async fn start(args: Args) -> MartinResult<()> {
     #[cfg(all(feature = "webui", not(docsrs)))]
     let web_ui_mode = config.srv.web_ui.unwrap_or_default();
 
+    let base_url = if let Some(ref prefix) = config.srv.route_prefix {
+        format!("http://{listen_addresses}{prefix}/")
+    } else {
+        format!("http://{listen_addresses}/")
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
```

File: martin/src/bin/martin.rs [hunk 16]
```diff
@@ -37,19 +37,24 @@ async fn start(args: Args) -> MartinResult<()> {
     #[cfg(all(feature = "webui", not(docsrs)))]
     let web_ui_mode = config.srv.web_ui.unwrap_or_default();
 
+    let route_prefix = config.srv.route_prefix.clone();
+
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
```

File: martin/src/bin/martin.rs [hunk 17]
```diff
@@ -37,19 +37,23 @@ async fn start(args: Args) -> MartinResult<()> {
...
     #[cfg(all(feature = "webui", not(docsrs)))]
     if web_ui_mode == martin::config::args::WebUiMode::EnableForAll {
-        tracing::warn!("Web UI is enabled for all connections at http://{listen_addresses}/");
+        tracing::info!("Martin server is now active at {base_url}");
     } else {
         info!(
             "Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
         );
+        info!("Martin server is now active. See {base_url}catalog to see available services");
     }
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs]:
```suggestion
}
#[cfg(not(all(feature = "webui", not(docsrs))))]
        info!("Martin server is now active. See {base_url}catalog to see available services");
```

File: martin/src/bin/martin.rs [hunk 18]
```diff
@@ -37,19 +37,24 @@ async fn start(args: Args) -> MartinResult<()> {
...
-        tracing::warn!("Web UI is enabled for all connections at http://{listen_addresses}/");
+        tracing::info!("Martin server is now active at {base_url}");
     } else {
         info!(
             "Web UI is disabled. Use `--webui enable-for-all` in CLI or a config value to enable it for all connections."
         );
     }
-
+    #[cfg(not(all(feature = "webui", not(docsrs))))]
+    info!("Martin server is now active. See {base_url}catalog to see available services");
```
Comment (CommanderStorm) [inline martin/src/bin/martin.rs:57]:
```suggestion
    info!("Martin server is now active. See {base_url}catalog to see available services");

```

File: martin/src/bin/martin.rs (hunk 12 above)
Comment (nyurik) [reply martin/src/bin/martin.rs:50]: we may want to even add a comment about that - as i think i caught this one before too :)
