### PR TITLE
fix: restrict zooming and panning on data inspector

### LINKED ISSUE #2325: Restrict zooming and panning on the data inspector
Currently, we just show 0/0/0 in the inspector in the fronted.

This works for global datasets, but does not for more local datasets.
For these smaller datasets, we should restrict our zoom to the extent of the dataset.

As a visualisation:

Image

Currently shows as:

Image

On the frontend, we currently don't store the bbox + min/maxzoom.
We need to either:
- take data that maplibre-gl-js already fetched
- or fetch the tilejson ourselves

The data about this is not avaliable in the catalog, so won't be avaliable to the frontend without extra work.

### PR DESCRIPTION
**Pull request by manbhav234**
This PR fixes #2325

The TileJson is being fetched again to set the bounds and zoom values properly. The main map component has been shifted to a new component, wrapping it inside suspense to fetch the tileJson asynchronously. The tiles now load in the restricted area if the data is local.

One peculiar thing I noticed:
When setting the bounds, if the first value for west is -180, it leads to the following error:
Screenshot 2026-02-26 at 7 58 32 PM

If the value is less than -180 or you set it to -179 or less if it is -180, the error vanishes. I haven't looked too deep as to why this is happening. Maybe it's because of how setMaxBounds internally manipulates these values that lead to a NaN. But not too sure.

### CODE REVIEW

File: martin/martin-ui/src/components/dialogs/tile-inspect-map.tsx [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+      console.error('Map not found despite being initialized, this cannot happen');
+      return;
+    }
+    const map = mapRef.current.getMap();
+    const tileJson: TileJson = tileJsonOperation.data;
+    //Error when first value set to -180. it gets resolved on setting to -179 or lower. Other values work fine.
+    map.setMaxBounds([
+      [tileJson.bounds[0] === -180 ? -179 : tileJson.bounds[0], tileJson.bounds[1]],
+      [tileJson.bounds[2], tileJson.bounds[3]],
+    ]);
```
Comment (CommanderStorm) [inline martin/martin-ui/src/components/dialogs/tile-inspect-map.tsx]: lets be a bit more fuzzy about this 😉

```suggestion
    if (tileJson.bounds) {
      const [west, south, east, north] = tileJson.bounds;
      const isWorld =
        west <= -179 &&
        east >= 179;
      if (!isWorld) {
          map.setMaxBounds([
            [west, south],
            [east, north],
          ]);
      }
    }
```

**Review by CommanderStorm — APPROVED** [review]
Nice work, thank you ❤️
