### PR TITLE
Fix tilejson scheme

### LINKED ISSUE #1716: MapLibre-GL-JS problem with MBTile source
At the moment I face a problem using MapLibre GL JS and an MBTile source.
The tilejson responds with `scheme: tms` what is correct I've read because mbtiles are always `tms`?!?!
It looks like MapLibre GL JS is taking care of that and requests a inverted y axis, but in the mbtiles mod the y axis is inverted again: 
https://github.com/maplibre/martin/blob/00757ee708e18a654e03e78ba843d106c2593010/mbtiles/src/mbtiles.rs#L144 
So I'm getting no tiles for the specified region. If I point maplibe to a modified tilejson with `scheme: xyz` it will work.

### PR DESCRIPTION
**Pull request by mr-sven**
This fix #1716

### CODE REVIEW

File: mbtiles/src/metadata.rs [hunk 1]
```diff
@@ -111,7 +111,10 @@ impl Mbtiles {
         let query = query!("SELECT name, value FROM metadata WHERE value IS NOT ''");
         let mut rows = query.fetch(&mut *conn);
 
-        let mut tj = tilejson! { tiles: vec![] };
+        let mut tj = tilejson! {
+            tiles: vec![],
+            scheme: "xyz".to_string()
```
Comment (nyurik) [inline mbtiles/src/metadata.rs]: I don't think we need this - the default of `xyz` is sufficient

File: mbtiles/src/metadata.rs [hunk 2]
```diff
@@ -136,6 +139,7 @@ impl Mbtiles {
                         tj.other.insert(name, Value::String(value));
                     }
                     "agg_tiles_hash" => agg_tiles_hash = Some(value),
+                    "scheme" => (), // ignore scheme because it defaults to xyz
```
Comment (nyurik) [inline mbtiles/src/metadata.rs]: I see the issue - so basically we treat `schema` as a custom field, and because your mbtiles just happen to have it set, I copy it into the output as is... I see how this could be a problem.

We should not silently ignore it though, so perhaps something like this?  (haven't tested, might use some wordsmithing)

```suggestion
                    "scheme" => {
                        if value != "tms" {
                            warn!("File {file} has an unexpected metadata value schema='{value}'. Only 'tms' is supported. Ignoring.")
                        }
                    }
```

File: mbtiles/src/metadata.rs [hunk 3]
```diff
@@ -136,6 +136,11 @@ impl Mbtiles {
                         tj.other.insert(name, Value::String(value));
                     }
                     "agg_tiles_hash" => agg_tiles_hash = Some(value),
+                    "scheme" => {
+                        if value != "tms" {
+                            warn!("File {file} has an unexpected metadata value schema='{value}'. Only 'tms' is supported. Ignoring.")
```
Comment (nyurik) [inline mbtiles/src/metadata.rs]: Typo, lets use a var instead

```suggestion
                            warn!("File {file} has an unexpected metadata value {name}='{value}'. Only 'tms' is supported. Ignoring.")
```

**Review by nyurik — APPROVED** [review]
